FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt
RUN python -m pip install pytest kafka-python

COPY tests /tests
COPY config.ini /tests/

#RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /tests
#USER appuser

WORKDIR /tests
CMD ["python", "server.py", "config.ini"]

EXPOSE 6064